### ISSUE TITLE
Error when running single test case

### ISSUE THREAD

**Issue by ducminhgd** [pybee/cricket#53]
It's OK if choose "run all" or "run selected" with the script file selected, but when I choose a test case then click "run selected", an error occured:

> Traceback (most recent call last):
> File "manage.py", line 10, in <module>
> execute_from_command_line(sys.argv)
> File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
> utility.execute()
> File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
> self.fetch_command(subcommand).run_from_argv(self.argv)
> File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 50, in run_from_argv
> super(Command, self).run_from_argv(argv)
> File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
> self.execute(*args, **options.__dict__)
> File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 71, in execute
> super(Command, self).execute(*args, **options)
> File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
> output = self.handle(*args, **options)
> File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 88, in handle
> failures = test_runner.run_tests(test_labels)
> File "/usr/local/lib/python2.7/dist-packages/django/test/runner.py", line 144, in run_tests
> suite = self.build_suite(test_labels, extra_tests)
> File "/usr/local/lib/python2.7/dist-packages/django/test/runner.py", line 63, in build_suite
> tests = self.test_loader.loadTestsFromName(label)
> File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
> module = __import__('.'.join(parts_copy))
> ImportError: No module named myapp

**Comment by freakboy3742** [comment]
Closing; this may have been an issue, but it isn't any longer.
