### ISSUE TITLE
AttributeError: 'TestMethod' object has no attribute 'items'

### ISSUE THREAD

**Issue by coler-j** [pybee/cricket#79]
```
Traceback (most recent call last):
  File "C:\Users\Cole Jancsar\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Cole Jancsar\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cole Jancsar\Desktop\Testing practice\obey_goat_project\venv\Scripts\cricket-django.exe\__main__.py", line 9, in <module>
  File "c:\users\cole jancsar\desktop\testing practice\obey_goat_project\venv\lib\site-packages\cricket\django\__main__.py", line 9, in main
    cricket_main(DjangoProject)
  File "c:\users\cole jancsar\desktop\testing practice\obey_goat_project\venv\lib\site-packages\cricket\main.py", line 90, in main
    view.project = project
  File "c:\users\cole jancsar\desktop\testing practice\obey_goat_project\venv\lib\site-packages\cricket\view.py", line 509, in project
    self._add_test_module('', testModule)
  File "c:\users\cole jancsar\desktop\testing practice\obey_goat_project\venv\lib\site-packages\cricket\view.py", line 490, in _add_test_module
    for testMethod_name, testMethod in sorted(testCase.items()):
AttributeError: 'TestMethod' object has no attribute 'items'
```

**Comment by coler-j** [comment]
- Django: Version: 2.1.7
- Using standard Django TestCases

**Comment by freakboy3742** [comment]
We've removed the Django backend, so this bug report is now moot.
